import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '#/components/header';
import ThemeProvider from '#/components/theme-provider';
import { Toaster } from '#/components/ui/toaster';
import { cn } from '#/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang='en'
      className='min-h-screen bg-background'
      suppressHydrationWarning>
      <body
        className={cn(
          inter.className,
          'grid min-h-screen grid-rows-[auto_1fr]'
        )}>
        <ThemeProvider
          attribute='class'
          defaultTheme='light'
          enableSystem
          disableTransitionOnChange>
          <Header />
          <div id='main-content'>{children}</div>
          <Toaster />
        </ThemeProvider>
      </body>
    </html>
  );
}
