name: PR Testing
on:
  pull_request: 
    branches: ["main"]

permissions:
  contents: read 

defaults:
  run:
    shell: bash

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Lint 
        run: npm run lint
