name: News Aggregate Pipeline
on:
  workflow_dispatch:
  schedule:
    - cron: '00 00,12 * * *'

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

# Allow one concurrent deployment
concurrency:
  group: 'pipeline'
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

env:
  # event registry values
  NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
  NEWS_API_TOPIC_URI: ${{ secrets.NEWS_API_TOPIC_URI }}
  # drizzle values
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  # watsonx values
  WATSONX_AI_AUTH_TYPE: 'iam'
  WATSONX_AI_SERVICE_URL: 'https://us-south.ml.cloud.ibm.com'
  WATSONX_AI_APIKEY: ${{ secrets.WATSONX_AI_APIKEY }}
  WATSONX_AI_PROJECT_ID: ${{ secrets.WATSONX_AI_PROJECT_ID }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Source risk events
        run: tsx --conditions=react-server ./src/pipeline/aggregate/index.ts

      - name: Map risk events to suppliers
        run: tsx --conditions=react-server ./src/pipeline/map-relations/index.ts

